# Generated by Django 3.2.5 on 2024-11-27 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0004_auto_20241125_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrmenu.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrmenu.product')),
            ],
        ),
    ]
